name: Rust

on: [push, pull_request]

jobs:
  vanilla_build:
    name: Vanilla Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all
  all_features_build:
    name: All Features Enabled Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update
    - name: Build
      run: cargo build --verbose --all-features --all
    - name: Run tests
      run: cargo test --verbose --all-features --all
    - name: Build Examples
      run: cargo build --examples --all-features --all
  msrv:
    name: Minimum Supported Rust Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain add 1.63
    - name: Downgrade unicode-ident
      run: cargo update --package unicode-ident --precise 1.0.22
    - name: Downgrade syn
      run: cargo update --package syn --precise 2.0.106
    - name: Downgrade quote
      run: cargo update --package quote --precise 1.0.41
    - name: Downgrade proc-macro2
      run: cargo update --package proc-macro2 --precise 1.0.103
    - name: Build
      run: cargo +1.63 check --lib --all-features
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update
    - run: rustup component add clippy
    - run: cargo clippy --all-features --workspace -- -Dclippy::all
  rustfmt:
    name: Check rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update
    - run: rustup component add rustfmt --toolchain stable
    - run: cargo +stable fmt --all -- --check
  fuzz:
    name: Run `int_in_range` fuzz target
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update
    - name: "Install nightly"
      run: rustup toolchain install nightly && rustup default nightly
    - name: "Install `cargo-fuzz`"
      run: cargo install cargo-fuzz
    - name: "Fuzz for 3 minutes"
      run: cargo fuzz run int_in_range -- -max_total_time=$((3 * 60))
  no_std_build:
    name: no_std Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - run: cargo build --verbose --no-default-features
      - run: cargo test --verbose --no-default-features
      - run: cargo build --verbose --no-default-features --features=alloc
      - run: cargo test --verbose --no-default-features --features=alloc
